apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qyva9zwvl-nodejs 
  janus-idp.io/tekton: qyva9zwvl-nodejs
  backstage.io/kubernetes-id: qyva9zwvl-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qyva9zwvl-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml