apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qyva9zwvl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qyva9zwvl-nodejs 
  name: qyva9zwvl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: qyva9zwvl-nodejs 
